server.port=8080

spring.application.name=Budget Buddy - Aplicativo de Gestao Financeira
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/bancodados
spring.datasource.username=bancodados
spring.datasource.password=bancodados
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true